spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - OPTIONS
              - UPDATE
              - DELETE
              - PATCH
              - POST
      routes:
        - id: public
          uri: https://g-poc-service-without-security.herokuapp.com/api/public
          predicates:
            - Path=/api/public
            - Method=GET,OPTIONS

        - id: private
          uri: https://g-poc-service-without-security.herokuapp.com/api/private
          predicates:
            - Path=/api/private
            - Method=GET,OPTIONS

        - id: users-update
          uri: https://g-poc-user-wrapper.herokuapp.com/api/v0/users
          predicates:
            - Path=/api/v0/users/**
            - Method=PATCH,OPTIONS
          filters:
            - UpdateUserAuthorizationFilter

        - id: users-CRD
          uri: https://g-poc-user-wrapper.herokuapp.com/api/v0/users
          predicates:
            - Path=/api/v0/users/**
            - Method=GET,POST,DELETE,OPTIONS
          filters:
            - AuthorizationFilter

        - id: create-interrogation
          uri: https://g-poc-service-without-security.herokuapp.com/api/interrogation
          predicates:
            - Path=/api/interrogation
          filters:
            - AuthorizationFilter

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://jgarbora.eu.auth0.com/
          audience: geneva-poc-api

auth0:
  management:
    api:
      clientSecret: ${AUTH0_API_CLIENT_SECRET}
      clientId: ${AUTH0_API_CLIENT_ID}

logging:
  level:
    com:
      g:
        g:
          apigateway:
            filter: off
    org:
      springframework:
        cloud:
          gateway: off
        security: trace
        cache: off

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8082



